# Generated by Django 5.2.3 on 2025-06-26 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_customuser_lastname_customuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='lastname',
            field=models.TextField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.TextField(blank=True, max_length=30),
        ),
    ]
