# Generated by Django 5.2.3 on 2025-06-26 02:04

import dashboard.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', dashboard.models.CustomUserManager()),
            ],
        ),
    ]
